name: Claude ML + Security + API Key Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  claude_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Extract code and diff
        run: |
          mkdir -p extracted
          for nb in $(find . -name "*.ipynb"); do
            jupyter nbconvert --to script "$nb" --output-dir extracted
          done
          find . -name "*.py" -exec cp {} extracted/ \;
          cat extracted/*.py > combined_code.py || echo "# no code" > combined_code.py
          git fetch origin main || true
          git diff origin/main...HEAD > diff.txt || echo "# no diff" > diff.txt

      - name: Claude ML + Security + API Key Review
        id: claude_review
        uses: anthropics/claude-code-action@v1
        with:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.TESTING_TOKEN }}
          prompt: |
            You are a **senior ML engineer and security auditor**.

            Review this PR for:
            1. Machine Learning correctness (data leakage, reproducibility, random seeds)
            2. Security vulnerabilities (RCE, pickle, SQLi)
            3. Hardcoded secrets, API keys, or tokens in the code (anything that looks like keys, tokens, or passwords)
            4. General code hygiene and reproducibility

            Flag ANY of the following patterns as HIGH severity:
            - "api_key", "apikey", "api-key", "token", "secret", "password"
            - Keys starting with: "sk_", "pk_", "AIza", "ghp_", "xoxb-", "ya29.", "eyJ"
            - Anything that looks like a base64 string longer than 30 chars
            - Any variable or string literal containing the above words

            Output format:
            - ❌ [HIGH] <file>:<line> – <reason>
            - 🟡 [MEDIUM] <file>:<line> – <reason>
            - ✅ Summary line at the end:
              "✅ All checks passed: No high or medium severity issues detected."

            --- CODE DIFF ---
            $(cat diff.txt)

            --- FULL CODE ---
            $(cat combined_code.py)

      - name: Save Claude output
        run: |
          output="${{ steps.claude_review.outputs.output }}"
          if [ -z "$output" ]; then
            echo "✅ Claude review completed: No high or medium severity issues detected." > claude_output.txt
          else
            echo "$output" > claude_output.txt
          fi

      - name: Post Claude comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TESTING_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('claude_output.txt', 'utf8').trim();

            const issueNumber =
              context.payload.pull_request?.number ||
              context.payload.issue?.number ||
              (context.payload.comment?.issue_url?.split('/').pop());

            if (!issueNumber) {
              core.warning("⚠️ No pull request or issue number found — skipping comment.");
            } else {
              await github.rest.issues.createComment({
                issue_number: issueNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output,
              });
            }

      - name: Block merge if issues found
        run: |
          if grep -q "❌" claude_output.txt || grep -q "HIGH" claude_output.txt; then
            echo "❌ Claude review failed — critical issues detected."
            exit 1
          else
            echo "✅ No critical issues detected. Merge allowed."
          fi
