name: Claude Combined Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write
  actions: read

jobs:
  claude_review:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Step 2: Extract code and prepare diff (for ML + security review)
      - name: Extract code and diff
        run: |
          mkdir -p extracted
          # Convert notebooks to .py
          for nb in $(find . -name "*.ipynb"); do
            jupyter nbconvert --to script "$nb" --output-dir extracted
          done
          # Copy all Python files
          find . -name "*.py" -exec cp {} extracted/ \;
          # Combine all code
          cat extracted/*.py > combined_code.py || echo "# no code" > combined_code.py
          # Create PR diff
          git fetch origin main || true
          git diff origin/main...HEAD > diff.txt || echo "# no diff" > diff.txt

      # Step 3: Run Claude ML + Security + API Key Review
      - name: Claude Review
        id: claude_review
        uses: anthropics/claude-code-action@v1
        with:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.CLAUDE_GITHUB_PAT }}
          prompt: |
            You are a **senior ML engineer & security auditor**. Review the PR for:

            1. Machine Learning correctness (data leakage, random seeds, reproducibility)
            2. Security vulnerabilities (RCE, unsafe deserialization, injection, data leaks)
            3. Hardcoded secrets or API keys (ANYTHING that looks like 'api_key', 'token', 'password', 'sk_test_', 'sk_live_')
            4. Code hygiene & reproducibility

            Focus only on new code introduced in this PR.

            ---
            ## CODE TO REVIEW:
            DIFF:
            ```
            $(cat diff.txt)
            ```
            FULL CODE:
            ```
            $(cat combined_code.py)
            ```

            ---
            ## OUTPUT FORMAT:
            - For each issue, include:
              - File & Line
              - Severity: High / Medium
              - Category (e.g., secret_exposure, pickle_injection, data_leakage)
              - Description
              - Exploit / Impact
              - Fix Recommendation
            - Only report High or Medium severity with confidence ≥ 8
            - Explicitly flag any hardcoded API keys as HIGH severity

            IMPORTANT: Even if no issues are found, explicitly include a final summary line like:
            "✅ All checks passed: No high or medium severity issues detected."

      # Step 4: Save Claude output (fallback if empty)
      - name: Save Claude output
        run: |
          output="${{ steps.claude_review.outputs.output }}"
          if [ -z "$output" ]; then
            echo "✅ Claude review completed: No high or medium severity issues detected."
          else
            echo "$output"
          fi > claude_output.txt

      # Step 5: Post review comment to PR or issue
      - name: Post Claude comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('claude_output.txt', 'utf8').trim();
            if (github.event_name.startsWith("pull_request")) {
              await github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            } else if (github.event_name.startsWith("issue")) {
              await github.rest.issues.createComment({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            }

      # Step 6: Block merge if HIGH issues found
      - name: Block merge if issues found
        if: github.event_name == 'pull_request'
        run: |
          if grep -q "❌" claude_output.txt || grep -q "HIGH" claude_output.txt; then
            echo "Claude review failed — issues detected. Blocking merge."
            exit 1
          else
            echo "✅ No critical issues detected. Merge allowed."
          fi
