name: Claude Python Review
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  python_review:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies (optional but recommended)
      - name: Install dependencies
        run: pip install -U pip

      # Step 3: Get diff of the Python file against main
      - name: Get PR diff
        id: get_diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD -- 'train_model_good.py' > diff.txt
          cat diff.txt || echo "No diff found."

      # Step 4: Extract the Python file content
      - name: Read Python file
        id: read_py
        run: |
          if [ -f train_model_good.py ]; then
            cat train_model_good.py > train_model_combined.py
          else
            echo "# train_model_good.py not found" > train_model_combined.py
          fi

      # Step 5: Run Claude Review
      - name: Run Claude Review
        id: run_claude
        uses: anthropics/claude-code-action@v1
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-3-5-sonnet
          input: |
            You are a senior ML code reviewer.
            Review the file **train_model_good.py** for:
            - Machine Learning best practices (no data leakage, reproducibility)
            - Security (no API keys, secrets, model files)
            - Code quality (clean code, modular structure, comments)
            - Performance (vectorization, efficient loops)
            - Documentation (docstrings, comments)
            Use this checklist as a guide:
            $(cat .github/claude-checklist.yml)

            Pull request diff:
            $(cat diff.txt)

            Full file content:
            $(cat train_model_combined.py)

            Return a Markdown report with:
            ✅ PASS / ❌ FAIL per rule,
            brief explanations,
            and a summary section.

      # Step 6: Save Claude's output to a text file
      - name: Save Claude output
        run: echo "${{ steps.run_claude.outputs.output }}" > claude_output.txt

      # Step 7: Post Claude's review as a PR comment
      - name: Post Claude Review Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('claude_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      # Step 8: Block merging if FAIL found
      - name: Block merge if issues found
        run: |
          if grep -q "FAIL" claude_output.txt; then
            echo "❌ Claude review failed — please fix issues before merging."
            exit 1
          else
            echo "✅ All checks passed."
          fi
