name: Claude ML Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ml_review:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (fetch all commits)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure full history for diff

      # Step 2: Get PR diff (handles missing main branch safely)
      - name: Get PR diff
        id: get_diff
        run: |
          git fetch origin main || echo "No main branch found"
          if git rev-parse --verify origin/main >/dev/null 2>&1; then
            git diff origin/main...HEAD -- 'train_model_good.py' > diff.txt || echo "No diff found"
          else
            echo "No main branch found, using fallback diff."
            git diff HEAD~1 -- 'train_model_good.py' > diff.txt || echo "No diff found"
          fi
          cat diff.txt || echo "No differences to show."

      # Step 3: Run Claude ML Code Review
      - name: Run Claude ML Review
        id: run_claude
        uses: anthropics/claude-code-action@v1
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-3-5-sonnet
          input: |
            You are a senior ML engineer reviewing code.
            The file under review is a Python machine learning script named `train_model_good.py`.

            Review the code for:
            - ✅ Correctness: data leakage, seed fixing, train-test split, model saving.
            - ⚙️ Security: no API keys, no sensitive data paths, safe imports.
            - 🧹 Code quality: clear structure, functions documented, no leftover print/debug.
            - 🧪 Reproducibility: same random seeds, versioned dependencies.
            - 📊 ML Best Practices: scaling, validation, overfitting detection.

            Use this checklist if available:
            $(cat .github/claude-checklist.yml 2>/dev/null || echo "No checklist file found.")

            Code diff:
            $(cat diff.txt)

            Return a **Markdown review report** containing:
            - ✅ PASS / ❌ FAIL for each check.
            - Short explanation for each issue.
            - A final summary section with an overall rating (Good / Needs Improvement / Risky).

      # Step 4: Save Claude output
      - name: Save Claude output
        run: echo "${{ steps.run_claude.outputs.output }}" > claude_output.txt

      # Step 5: Post Claude Review as PR comment
      - name: Post Claude Review Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('claude_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      # Step 6: Block merge if issues found
      - name: Block merge if issues found
        run: |
          if grep -q "FAIL" claude_output.txt; then
            echo "❌ Claude Review: Issues found. Please fix before merging."
            exit 1
          else
            echo "✅ Claude Review: All checks passed."
          fi
